
# Trabajo con NumPy

Sinonimo de *Numerical Python*, `numpy` es una librería que proporciona herramientas para trabajar con alto rendimiento sobre arreglos multidimensionales. 


## Características
Dentro de las principales características de `numpy` se encuentran:
- Ofrece un poderoso objeto para manipular arreglos multidimensionales: `ndarray`.
- Posee herramientas para realizar operaciones matemáticas y lógicas sobre arreglos, operaciones relacionadas con algebra lineal, transformadas de Fourier, entre otras.

Para importar los módulos de la librería `numpy`, por convención se utiliza:

In [3]:
#importamos Numpy con el alias np
import numpy as np


## Arrays


Las funcionalidades de `numpy` se basan en en el objeto `ndarray`.

Un `ndarray`, también conocido por el alias de `array`, es un arreglo N-dimensional con elementos del mismo tipo e indexado por una tupla de enteros positivos.


```python
a = numpy.array(data, dtype = None, ndmin = 0, ...)
```
- data: datos de mismo tipo en forma de matriz o una secuencia anidada.
- dtype (opcional): tipos de datos deseados en el arreglo. 
- ndmin: especifica el número mínimo de dimensiones del arreglo resultante.

Crea una lista y conviértela en una matriz numpy:

In [4]:
a = np.array([[0,1,2,3],[4,5,6,7],[1,2,3,4]])  
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 2, 3, 4]])

O simplemente pasa una lista directamente:

In [5]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

Pasa una lista de listas para crear una matriz multidimensional:

In [16]:
m = np.array([[0,1,2,3],[4,5,6,7],[1,2,3,4]])
m

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 2, 3, 4]])

Dentro de los principales atributos del objeto `ndarray`, se encuentran:
- `ndarray.shape`: tupla con las dimensiones del arreglo. 
- `ndarray.ndim`: numero de dimensiones del arreglo.
- `ndarray.size`: número de elementos del arreglo.
- `ndarray.dtype`: tipo de dato de los elementos del arreglo. 

In [17]:
m.shape

(3, 4)

In [18]:
m.ndim

2

In [19]:
m.size

12

In [8]:
m.dtype

dtype('int32')

Numpy cuenta con funciones especiales para crear arreglos con valores definidos por defecto, por ejemplo:
- **zeros**: crea arreglo solamente con 0's.
- **ones**: crea arreglo solamente con 1's.
- **eye**: crea una matriz identidad de tamaño n.
- **full**: crea un arreglo con un valor constante especificado.

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<br>`reshape` devuelve una matriz con los mismos datos en una nueva forma:

In [12]:
n = np.ones((6, 3))
n

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
n = n.reshape(2, 9) # reshape array to be 2x9
n

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
n = n.reshape(3, 6) # reshape array to be 1x18
n

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

<br>`arange` devuelve valores espaciados uniformemente dentro de un intervalo dado.

In [17]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>`linspace` devuelve números espaciados uniformemente en un intervalo especificado:

In [18]:
o = np.linspace(0, 4, 9) # Devuelve 9 valores espaciados uniformemente de 0 a 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

<br> `resize` cambia la forma y el tamaño de la matriz de forma definitiva:

In [19]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

<br>**diag** extrae una diagonal o construye una matriz diagonal:

In [20]:
np.diag([4,5,6,7])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

<br>Crea una matriz usando la lista de repetición (o ver `np.tile`):

In [21]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [26]:
np.tile(np.arange(1,4),(1,5))


array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

<br>Repite elementos de un array usando `repeat`.

In [23]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Vector aleatorio

In [28]:
np.random.seed(123)  #si defino la semilla, se reproducen los mismo números aleatorios


In [30]:
w = np.random.rand(10) #vector aleatorio de elementos uniformes entre 0 y 1
print(w)

[0.34317802 0.72904971 0.43857224 0.0596779  0.39804426 0.73799541
 0.18249173 0.17545176 0.53155137 0.53182759]


In [32]:
x = np.random.randn(10) #vector aleatorio de elementos normales estandar
print(x)

[-0.14006872 -0.8617549  -0.25561937 -2.79858911 -1.7715331  -0.69987723
  0.92746243 -0.17363568  0.00284592  0.68822271]


In [28]:
y = np.random.randint(0,10,10) #vector aleatorio de elementos enteros
print(y)

[9 3 5 2 5 9 9 8 7 1]


## Matrices

In [35]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11] , [3,5,6,9]])
print(np.shape(a))
print(a)

(4, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 3  5  6  9]]


In [32]:
#Creación de una matriz diagonal

#Primero un rango lineal
a = np.arange(5)
print(a)

#Y ahora lo convertimos en diagonal
diagonal = np.diag(a)
print(diagonal)

[0 1 2 3 4]
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


In [37]:
#Matriz a base de "tiles" (baldosas)
ar = np.array([[6,7],[8,9]])
print(ar)
tiles = np.tile(ar,(2,3))
print(tiles)

[[6 7]
 [8 9]]
[[6 7 6 7 6 7]
 [8 9 8 9 8 9]
 [6 7 6 7 6 7]
 [8 9 8 9 8 9]]


In [38]:
#Cambio de forma de un vector

#Creamos un vector lineal y lo reorganizamos como matriz 3x3
x = np.arange(9)
print(x)
x = x.reshape(3,3)
print(x)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Trabajo con matrices

In [39]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

<br> Utiliza `vstack` para apilar las matrices o arrays en secuencia verticalmente (en sentido de fila):

In [40]:
np.vstack((p, 2*p))

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

<br>Usa `hstack` para apilar las matrices en secuencia horizontalmente (en sentido de columna):

In [41]:
np.hstack((p, 2*p))

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<br>Usa `column_stack` para concatenar por matrices horizontalmente (permite concatenar una matriz con un array unidimensional):

In [42]:
np.column_stack((p,[3,5]))

array([[1, 1, 1, 3],
       [1, 1, 1, 5]])

### Operaciones con arrays

Usa `+`, `-`,` * `,` / `y` ** `para realizar sumas, restas, multiplicaciones, divisiones y potencias por elementos:

In [43]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [44]:
print(x + 3) # adición por un escalar
print(x - 3) # resta por un escalar
print(x * 3) # multiplicación por un escalar
print(x / 3) # división por un escalar 

[4 5 6]
[-2 -1  0]
[3 6 9]
[0.33333333 0.66666667 1.        ]


In [45]:
print(x + y) # adición por elementos     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # resta por elementos      [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [46]:
print(x * y) # multiplicación por elementos  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # división por elementos        [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [47]:
print(x**2) # potenciación por elementos  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [48]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [49]:
np.dot(x,y)

32

Por otro lado, hay funciones universales que realizan operaciones con 2 arrays y regresan un array como salida.

In [50]:
np.add(x,y)

array([5, 7, 9])

In [51]:
np.multiply(x,y)

array([ 4, 10, 18])

In [52]:
np.power(x,y)

array([  1,  32, 729], dtype=int32)

<br>
Veamos las matrices de transposición. La transposición permuta las dimensiones de la matriz.

In [53]:
y

array([4, 5, 6])

In [54]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>La forma de la matriz `z` es` (2,3) `antes de la transposición:

In [55]:
z.shape

(2, 3)

<br>Usa `.T` para transponer una matriz:

In [56]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>El número de filas se ha intercambiado con el número de columnas.

In [57]:
z.T.shape

(3, 2)

Probando la multiplicación dot en matrices (producto matricial)

In [58]:
np.dot(z,z.T)

array([[  77,  405],
       [ 405, 2177]])

In [59]:
np.dot(z.T,z)

array([[ 272,  420,  600],
       [ 420,  650,  930],
       [ 600,  930, 1332]])

#### Determinante e inversa de una matriz

In [60]:
w = np.random.randint(0, 50, (4,4))
w

array([[41, 48, 27, 49],
       [22,  3,  3, 11],
       [21, 25, 39, 41],
       [34,  3, 11,  3]])

In [61]:
#Determinante: sobre matrices cuadradas
np.linalg.det(w)

405240.00000000093

In [62]:
#Inversa: sobre matrices cuadradas con determinante diferente de cero
np.linalg.inv(w)

array([[ 0.00217155,  0.01725891, -0.00876518,  0.02103938],
       [ 0.03800217, -0.07751456, -0.02611786,  0.02046195],
       [-0.01411509, -0.05763745,  0.02970092,  0.03597128],
       [-0.01085776,  0.09325091,  0.01655315, -0.05746965]])

## Funciones sobre arrays

*Numpy* tiene muchas funciones matemáticas integradas que se pueden realizar sobre arrays.

In [63]:
a = np.array([12, 13, 9, 3, 5])
a

array([12, 13,  9,  3,  5])

In [64]:
a.sum()  #suma

42

In [65]:
# alternativamente
np.sum(a)

42

In [66]:
a.prod()  #productoria

21060

In [67]:
a.max()  #maximo

13

In [68]:
a.min()  #mínimo


3

In [69]:
a.mean()  #promedio

8.4

In [70]:
np.median(a)  #mediana

9.0

In [71]:
a.std()   #desviación estándar

3.878143885933063

<br>`argmax` y` argmin` devuelven el índice del valor máximo y mínimo en la matriz:

In [72]:
a.argmax()

1

In [73]:
a.argmin()

3

Usar funciones trigonomértricas:

In [74]:
np.exp(a)

array([1.62754791e+05, 4.42413392e+05, 8.10308393e+03, 2.00855369e+01,
       1.48413159e+02])

In [75]:
np.log(a)

array([2.48490665, 2.56494936, 2.19722458, 1.09861229, 1.60943791])

In [76]:
np.sqrt(a)

array([3.46410162, 3.60555128, 3.        , 1.73205081, 2.23606798])

## Indexar/Seleccionar elementos

In [34]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

Usa la notación de corchetes para obtener el valor de un índice específico. Recuerda que la indexación comienza en 0:

In [35]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>Usa `:` para indicar un rango. `array[start:stop]`


Si se deja vacío `start` o `stop`, el inicio/final de la matriz será predeterminado:

In [36]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

<br>
Usa negativos para contar desde el final:

In [37]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

<br>Se puede usar un segundo `:` para indicar la magnitud del paso en el que se van a tomar los elmentos: `array[start:stop:stepsize]`

Aquí estamos comenzando en el quinto elemento desde el final, y contando en 2 hacia atrás hasta llegar al comienzo de la matriz:

In [38]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [82]:
s[-5::2]

array([ 64, 100, 144], dtype=int32)

<br> **Para matrices:** Usa la notación de paréntesis para dividir: `matriz [fila, columna]`

In [83]:
r = np.random.randint(0, 50, (10,10))
r

array([[30,  6,  9, 23, 14, 38, 19,  6, 12, 27],
       [38, 17, 46, 10, 35, 35,  1, 47, 45, 16],
       [ 5, 40, 45, 22, 46, 15, 40, 25, 45, 49],
       [ 0, 35, 29,  1, 19,  4, 30,  7, 29, 38],
       [ 1, 12,  3, 44,  7, 38, 24,  6, 13, 28],
       [44, 20, 36, 48, 32, 40, 24, 45, 13,  8],
       [14,  6,  1, 30,  6, 40, 10, 12, 12, 25],
       [42, 49,  7, 13, 44,  1, 41, 14, 23, 33],
       [ 3, 17, 24, 46, 23,  5, 33, 37,  2, 18],
       [46, 45, 35, 18, 27, 46,  9, 17,  3, 11]])

In [84]:
r[2, 2]

45

<br>Y usa `:` para seleccionar un rango de filas o columnas. ¡Ten en cuenta que el índice 6 no existe!

In [85]:
r[3, 3:6]

array([ 1, 19,  4])

In [86]:
r[0:2,0:3]

array([[30,  6,  9],
       [38, 17, 46]])

In [87]:
r[1:2, 2:]

array([[46, 10, 35, 35,  1, 47, 45, 16]])

<br>Aquí estamos seleccionando todas las filas hasta (y sin incluir) la fila 2, y todas las columnas hasta (y sin incluir) la última columna:

In [88]:
r[:2, :-1]

array([[30,  6,  9, 23, 14, 38, 19,  6, 12],
       [38, 17, 46, 10, 35, 35,  1, 47, 45]])

In [89]:
r[0:2, 0:-1]

array([[30,  6,  9, 23, 14, 38, 19,  6, 12],
       [38, 17, 46, 10, 35, 35,  1, 47, 45]])



Esta es una porción de la última fila, y solo los elementos pares:

In [90]:
r[-1, ::2]

array([46, 35, 27,  9,  3])

<br>También podemos realizar indexación condicional. Aquí estamos seleccionando valores de la matriz que son mayores que 30:

In [91]:
r[r > 28]

array([30, 38, 38, 46, 35, 35, 47, 45, 40, 45, 46, 40, 45, 49, 35, 29, 30,
       29, 38, 44, 38, 44, 36, 48, 32, 40, 45, 30, 40, 42, 49, 44, 41, 33,
       46, 33, 37, 46, 45, 35, 46])

<br>Aquí estamos asignando el valor 30 a todos los valores de la matriz que son mayores que 30.

In [92]:
r[r > 30] = 30
r

array([[30,  6,  9, 23, 14, 30, 19,  6, 12, 27],
       [30, 17, 30, 10, 30, 30,  1, 30, 30, 16],
       [ 5, 30, 30, 22, 30, 15, 30, 25, 30, 30],
       [ 0, 30, 29,  1, 19,  4, 30,  7, 29, 30],
       [ 1, 12,  3, 30,  7, 30, 24,  6, 13, 28],
       [30, 20, 30, 30, 30, 30, 24, 30, 13,  8],
       [14,  6,  1, 30,  6, 30, 10, 12, 12, 25],
       [30, 30,  7, 13, 30,  1, 30, 14, 23, 30],
       [ 3, 17, 24, 30, 23,  5, 30, 30,  2, 18],
       [30, 30, 30, 18, 27, 30,  9, 17,  3, 11]])

### Slicing

In [93]:
x = np.array([1,2,3])
x[1:]

array([2, 3])

In [94]:
r[1:2, 2:]

array([[30, 10, 30, 30,  1, 30, 30, 16]])

In [95]:
r[0:2,0:3]

array([[30,  6,  9],
       [30, 17, 30]])

In [96]:
# Numpy permite crear máscaras fácilmente usando condiciones booleanas
r>25

array([[ True, False, False, False, False,  True, False, False, False,
         True],
       [ True, False,  True, False,  True,  True, False,  True,  True,
        False],
       [False,  True,  True, False,  True, False,  True, False,  True,
         True],
       [False,  True,  True, False, False, False,  True, False,  True,
         True],
       [False, False, False,  True, False,  True, False, False, False,
         True],
       [ True, False,  True,  True,  True,  True, False,  True, False,
        False],
       [False, False, False,  True, False,  True, False, False, False,
        False],
       [ True,  True, False, False,  True, False,  True, False, False,
         True],
       [False, False, False,  True, False, False,  True,  True, False,
        False],
       [ True,  True,  True, False,  True,  True, False, False, False,
        False]])

In [97]:
# Extraer los valores de x que satisfacen la condición booleana. Para ello usamos la máscara
r[r>25]

array([30, 30, 27, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 29,
       30, 29, 30, 30, 30, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 27, 30])

In [98]:
# Sumar los valores de un arreglo 2D a lo largo del eje Y (columnas)
np.sum(r, axis=0)

array([173, 198, 193, 207, 216, 205, 207, 177, 167, 223])

In [99]:
# Sumar los valores de un arrego 2D a lo largo del eje X (filas)
np.sum(r, axis=1)

array([176, 224, 247, 179, 154, 245, 146, 208, 182, 205])

### Copiando arrays

<br>Para evitar esto, use `r.copy` para crear una copia que no afecte la matriz original:

In [100]:
copia_r = r.copy()
copia_r

array([[30,  6,  9, 23, 14, 30, 19,  6, 12, 27],
       [30, 17, 30, 10, 30, 30,  1, 30, 30, 16],
       [ 5, 30, 30, 22, 30, 15, 30, 25, 30, 30],
       [ 0, 30, 29,  1, 19,  4, 30,  7, 29, 30],
       [ 1, 12,  3, 30,  7, 30, 24,  6, 13, 28],
       [30, 20, 30, 30, 30, 30, 24, 30, 13,  8],
       [14,  6,  1, 30,  6, 30, 10, 12, 12, 25],
       [30, 30,  7, 13, 30,  1, 30, 14, 23, 30],
       [ 3, 17, 24, 30, 23,  5, 30, 30,  2, 18],
       [30, 30, 30, 18, 27, 30,  9, 17,  3, 11]])

### Iterando sobre matrices

Creamos una nueva matriz de 4 por 3 con números aleatorios de 0-9:

In [101]:
test = np.random.randint(0, 1000, (4,3))
test

array([[410,  92, 459],
       [906, 899, 557],
       [634, 442, 187],
       [407, 281, 795]])

Iterar por fila:

In [102]:
for row in test:
    print(row)

[410  92 459]
[906 899 557]
[634 442 187]
[407 281 795]




Iterar por índice y por fila con **enumerate**:

In [103]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [410  92 459]
row 1 is [906 899 557]
row 2 is [634 442 187]
row 3 is [407 281 795]


## Filtros en Arrays

Suponga que desea tomar el valor de una matriz `X` cuando el valor correspondiente en una condición es True, y de lo contrario tome el valor de la matriz `Y`. Dentro de *Numpy* hay una función llamada **np.where** que resuelve la situación anterior.

```python
result = np.where(cond, xarr, yarr)
```

In [104]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [105]:
np.where(xarr>1.3,0,1)

array([1, 1, 1, 0, 0])