# PRÁCTICA SEMANA 05

1.  Crea un objeto ndarray con elementos del 10 al 49. 

In [1]:
#importamos la librería numpy
#especializada en el cálculo numérico y el análisis de datos

import numpy as np
n = np.arange(10, 50, 1) #comienza en 10 cuenta hacia arriba de 1 en 1, termina antes de 50
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2.  Cree una matriz bidimensional, use el índice para obtener los datos en la segunda fila, primera columna y tercera fila, segunda columna. 

In [2]:
#importamos la librería numpy

import numpy as np

#crear matriz
a = np.array([[0,1,2,3],[4,5,6,7],[1,2,3,4]])  

b=a[1,0] #se indica la fila y la columna
c=a[2,1] #como inicia desde 0, al indicar 3ra fila colocamos: 2 y para 2da columna: 1
print(a)
print('\nsegunda fila, primera columna: ', b)
print('tercera fila, segunda columna: ', c)

[[0 1 2 3]
 [4 5 6 7]
 [1 2 3 4]]

segunda fila, primera columna:  4
tercera fila, segunda columna:  2


3.  Encontrar los índices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0] 

In [3]:
#importamos la librería numpy
import numpy as np
  
array = np.array([1, 0, 4, 0, 5, 0, 0, 12, 6, 7, 5, 0, 8]) 
  
print("Array actual:") 
print(array) 
  
print("\nÍndices que no son ceros del arreglo:") 
  
result = np.where(array != 0)[0] 
print(result) 

Array actual:
[ 1  0  4  0  5  0  0 12  6  7  5  0  8]

Índices que no son ceros del arreglo:
[ 0  2  4  7  8  9 10 12]


4.  Crear una matriz con valores al azar con forma 3x3x3

In [4]:
#importamos la librería numpy
import numpy as np
                          #vector aleatorio de elementos uniformes entre 0 y 1
x = np.random.rand(3,3,3) #numpy.random.rand() genera un array de forma especificada con valores aleatorios.
x

array([[[0.8548992 , 0.60767797, 0.85300179],
        [0.18364047, 0.27534846, 0.02905958],
        [0.12665091, 0.59282931, 0.17522134]],

       [[0.50589767, 0.85095801, 0.37646576],
        [0.32609648, 0.88554388, 0.54848983],
        [0.43312595, 0.41325911, 0.98979186]],

       [[0.08501316, 0.72482952, 0.89017131],
        [0.26938536, 0.99750389, 0.57086231],
        [0.43477204, 0.44432056, 0.27525131]]])

5.  Crea un tablero de ajedrez, con unos en las casillas negras y ceros en las blancas. 

In [9]:
#importamos la librería numpy
import numpy as np

casillero = np.array([[0,1],[1, 0]]) #se coloca el 0 como referencia al casillero de las piezas blancas
                                    #se coloca el 1 como referencia al casillero de las piezas negras
tablero = np.tile(casillero,[4,4]) #Construya una matriz repitiendo "casillero" la cantidad de veces dada por el tablero [4,4].
tablero

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

6.  Crea una matriz aleatoria 5x5 y halla los valores mínimo y máximo. 


In [6]:
#importamos la librería numpy
import numpy as np

#numpy.random.rand() genera un array de forma especificada con valores aleatorios.
#se coloca el rango 0, 60 y entre paréntesis fila x columna (5,5)
z = np.random.randint(0,60,(5,5)) 
print(z)
print(f'\nEl número mínimo es: ', z.min()) #método para hallar el nro mínimo
print(f'\nEl número mínimo es: ', z.max()) #método para hallar el nro máximo

[[25 51 45 20 43]
 [22  6 30 40  8]
 [39 47  5  8  7]
 [10  7 21 43 12]
 [52 24  6 37 49]]

El número mínimo es:  5

El número mínimo es:  52


7.  Crea 2 matrices de números enteros aleatorios del orden que desees, pero que sean del mismo orden, y realizar las operaciones de suma, resta, multiplicación escalar y división escalar. 

In [7]:
#importamos la librería numpy
import numpy as np

print('------- MATRIZ A ---------')

#numpy.random.rand() genera un array de forma especificada con valores aleatorios.

#se coloca el rango 0, 60 y entre paréntesis fila x columna
a = np.random.randint(0,60, (2, 2))
print(a)
print('\n------ MATRIZ B --------')
b = np.random.randint(0,60, (2, 2))
print(b)

print("\n----- SUMA --------------\n", a+b) # suma de a y b 

print("\n----- RESTA -------------\n", a-b) # resta de a y b 


print("\n--MULTIPLICACIÓN ESCALAR--\n", a*2) # multiplicación por un escalar
print("\n--MULTIPLICACIÓN ESCALAR--\n", b*2) 

print("\n-----DIVISIÓN ESCALAR-----\n", a/4) # división por un escalar
print("\n-----DIVISIÓN ESCALAR-----\n", b/4)


------- MATRIZ A ---------
[[43  4]
 [55 21]]

------ MATRIZ B --------
[[12 56]
 [50 37]]

----- SUMA --------------
 [[ 55  60]
 [105  58]]

----- RESTA -------------
 [[ 31 -52]
 [  5 -16]]

--MULTIPLICACIÓN ESCALAR--
 [[ 86   8]
 [110  42]]

--MULTIPLICACIÓN ESCALAR--
 [[ 24 112]
 [100  74]]

-----DIVISIÓN ESCALAR-----
 [[10.75  1.  ]
 [13.75  5.25]]

-----DIVISIÓN ESCALAR-----
 [[ 3.   14.  ]
 [12.5   9.25]]


8.  Crea 2 matrices de números aleatorios, una de orden mxn y otra de nxm (m puede ser igual a n) y realizar las operaciones de multiplicación matricial, y a esa matriz resultado sacar las operaciones determinante e inversa. Haga las mismas operaciones con las matrices transpuestas. 

In [1]:
#importamos la librería numpy
import numpy as np

#numpy.random.rand() genera un array de forma especificada con valores aleatorios.
#se indica que los numeros sean del 0 hasta 99 y entre paréntesis fila x columna y viceversa

array1 = np.random.randint(0,99, (2, 3))
array2 = np.random.randint(0,99, (3, 2))

print ('\nARRAY 1\n', array1)
print ('\nARRAY 2\n', array2)

print("\nMULTIPLICACIÓN MATRICIAL\n")
multi=np.dot(array1,array2)
print(multi) #equivale a array1@array2)

#Determinante: sobre matrices cuadradas
print("\nDETERMINANTE\n", np.linalg.det(multi))

#Inversa: sobre matrices cuadradas
print("\nINVERSA\n",  np.linalg.inv(multi))




ARRAY 1
 [[58 46 26]
 [49 73 91]]

ARRAY 2
 [[ 1 57]
 [22 17]
 [85 55]]

MULTIPLICACIÓN MATRICIAL

[[3280 5518]
 [9390 9039]]
[[3280 5518]
 [9390 9039]]

DETERMINANTE
 -22166099.999999985

INVERSA
 [[-0.00040778  0.00024894]
 [ 0.00042362 -0.00014797]]
